language: python
sudo: true
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - ./test/setup_test.sh

script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  - pip freeze
  # Code static analysis
  - pycodestyle --max-line-length=100 --exclude='.pyc,.cfg,.log,.cmake' --ignore='E402,W503' cmake_converter/
  - pylint --rcfile=.pylintrc cmake_converter/ cmake_converter/visual_studio
  # No pep257 currently (Code doc compliance)
  - pep257 --select=D300 cmake_converter
  # Code dynamic analysis
  - cd test/
  - coverage erase
  - pytest --cov=cmake_converter --cov-config=.coveragerc test_*.py
  - coverage report -m
  - cd ..


# specific call to launch coverage data into coveralls.io
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  - mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
  # - coveralls -v
  
